theme: jekyll-theme-primer

github:
  private: false
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/kenpusney/ng"

title: "The NG Programming Language"
description: "Just Another Programming Language"
