name: Bug Report
description: Create a report to help us improve the NG language.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: NG Code
      description: Your .ng file content or REPL code here
      placeholder: "// Your NG code here"
      render: ng
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command
      description: The ngi command you used
      placeholder: "ngi yourfile.ng"
      render: bash
    validations:
      required: false

  - type: textarea
    id: output
    attributes:
      label: Output
      description: The full output of the command, including any error messages
      placeholder: "Command output..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what should have happened...
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: false

  - type: input
    id: os_version
    attributes:
      label: OS Version
      description: What version of your operating system? (e.g., Sequoia 15.5, Ubuntu 22.04, Windows 11)
      placeholder: e.g., Sequoia 15.5
    validations:
      required: false

  - type: input
    id: ng_version
    attributes:
      label: NG Version
      description: What version of NG are you using? (e.g., master or a specific commit hash)
      placeholder: e.g., master
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any additional information...
    validations:
      required: false