name: build
on:
  - push
permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: read
  packages: read
  security-events: write
env:
  RUNNING_ON_GITHUB: "true"
  LLVM_PROFILE_FILE: default.profraw
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@a7a1a882e2d06ebe05d5bb97c3e1f8c984ae96fc
        with:
          version: "20"
      - uses: lukka/get-cmake@2ecc21724e5215b0e567bc399a2602d2ecb48541
      - run: mkdir -p build
      - run: cmake ../ -GNinja -DCMAKE_C_COMPILER=${{ env.LLVM_PATH }}/bin/clang -DCMAKE_CXX_COMPILER=${{ env.LLVM_PATH }}/bin/clang++
        working-directory: ./build
      - run: ninja
        working-directory: ./build
      - run: ./ng_test --reporter JUnit::out=ng_test.junit.xml --reporter console::out=-::colour-mode=ansi
        working-directory: ./build
      - run: ../utils/coverage_report.sh
        working-directory: ./build
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Codacy coverage
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        working-directory: ./build
