name: build
on:
  - push
env:
  RUNNING_ON_GITHUB: "true"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.7
        with:
          version: "20"
      - uses: lukka/get-cmake@latest
      - run: mkdir -p build
      - run: cmake ../ -GNinja -DCMAKE_C_COMPILER=${{ env.LLVM_PATH }}/bin/clang -DCMAKE_CXX_COMPILER=${{ env.LLVM_PATH }}/bin/clang++
        working-directory: ./build
      - run: ninja
        working-directory: ./build
      - run: ./ng_test
        working-directory: ./build
      - run: ../utils/coverage_report.sh
        working-directory: ./build
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
